replicaCount: 1

image:
  repository: kairoai.azurecr.io/kairoai-api-gateway
  tag: latest
  pullPolicy: IfNotPresent

command: []
args: []

service:
  enabled: true
  port: 8000
  targetPort: 8000

env:
  ENVIRONMENT: dev
  LOG_LEVEL: INFO

secretEnv: {}

envFrom: []

probes:
  enabled: true
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

resources: {}

serviceAccount:
  create: true
  name: ""
  annotations: {}
