keyVault:
  name: ""
  tenantId: ""
  userAssignedIdentityClientId: ""

secretName: kairoai-runtime-secrets

objects: []

syncPod:
  image: mcr.microsoft.com/azurelinux/base/core:3.0
  resources:
    requests:
      cpu: 5m
      memory: 16Mi
    limits:
      cpu: 25m
      memory: 32Mi
