apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}
spec:
  provider: azure
  secretObjects:
    - secretName: {{ .Values.secretName | quote }}
      type: Opaque
      data:
        {{- range .Values.objects }}
        - objectName: {{ .objectName | quote }}
          key: {{ .secretKey | quote }}
        {{- end }}
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ required "keyVault.userAssignedIdentityClientId is required" .Values.keyVault.userAssignedIdentityClientId | quote }}
    keyvaultName: {{ required "keyVault.name is required" .Values.keyVault.name | quote }}
    tenantId: {{ required "keyVault.tenantId is required" .Values.keyVault.tenantId | quote }}
    objects: |
      array:
        {{- range .Values.objects }}
        - |
          objectName: {{ .objectName }}
          objectType: secret
          objectVersion: ""
        {{- end }}
