fullnameOverride: kairoai-governance-service
replicaCount: 2

image:
  repository: acrkairoaihubci.azurecr.io/kairoai-governance-service
  tag: 2cfaadec0c72
  pullPolicy: IfNotPresent

env:
  ENVIRONMENT: prod
  LOG_LEVEL: INFO

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
